# Generated by Django 6.0.2 on 2026-05-08 16:57

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', unique=True, verbose_name='Contact📞')),
                ('adress', models.CharField(max_length=255, verbose_name='Adresse')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('tutor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuteur')),
                ('tutor_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', verbose_name='Contact du tuteur📞')),
                ('tutor_adress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse du tuteur')),
                ('transfered', models.BooleanField(default=False, verbose_name='Transféré')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'managed': True,
                'indexes': [models.Index(fields=['email'], name='patients_pa_email_81a01f_idx'), models.Index(fields=['contact'], name='patients_pa_contact_f3546e_idx'), models.Index(fields=['registered_at'], name='patients_pa_registe_713ace_idx'), models.Index(fields=['first_name', 'last_name'], name='patients_pa_first_n_26d9a0_idx'), models.Index(fields=['registered_at'], name='patient_registered_idx'), models.Index(fields=['transfered'], name='patients_pa_transfe_b46abd_idx'), models.Index(fields=['sexe'], name='patients_pa_sexe_1ad407_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_consultation', models.TextField(null=True, verbose_name='Raison de la Consultation')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnostic')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='staff.staff')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patients')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(choices=[('paracetamol', 'Paracétamol'), ('ibuprofene', 'Ibuprofène'), ('amoxicilline', 'Amoxicilline'), ('azithromycine', 'Azithromycine'), ('metformine', 'Metformine'), ('atorvastatine', 'Atorvastatine'), ('lisinopril', 'Lisinopril'), ('autre', 'Autre')], max_length=100, null=True, verbose_name='Nom du Médicament')),
                ('dosage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000)], verbose_name='Dosage (mg)')),
                ('frequency', models.CharField(choices=[('1x/day', '1 fois par jour'), ('2x/day', '2 fois par jour'), ('3x/day', '3 fois par jour'), ('4x/day', '4 fois par jour'), ('every_6h', 'Toutes les 6 heures'), ('every_8h', 'Toutes les 8 heures'), ('every_12h', 'Toutes les 12 heures'), ('as_needed', 'Si nécessaire')], max_length=20, null=True, verbose_name='Fréquence')),
                ('duration', models.CharField(max_length=100, null=True, verbose_name='Durée')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.consultation')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransferedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motif du Transfert')),
                ('receiving_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Établissement Receveur')),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_info', to='patients.patients')),
            ],
            options={
                'verbose_name': 'Patient Transféré',
                'verbose_name_plural': 'Patients Transférés',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(42)], verbose_name='Température (°C)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)], verbose_name='Fréquence cardiaque (bpm)')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Saturation en oxygène (%)')),
                ('blood_pressure', models.CharField(blank=True, max_length=7, null=True, verbose_name='Tension artérielle (mmHg)')),
                ('pulse', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)], verbose_name='Pouls (bpm)')),
                ('respiration_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(60)], verbose_name='Fréquence respiratoire (respirations/min)')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patients')),
            ],
            options={
                'verbose_name': 'Signe Vital',
                'verbose_name_plural': 'Signes Vitaux',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='Maladies Chroniques')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('long_term_treatments', models.TextField(blank=True, null=True, verbose_name='Traitements à Long Terme')),
                ('lifestyle_habits', models.TextField(blank=True, null=True, verbose_name='Habitudes de Vie')),
                ('family_history', models.TextField(blank=True, null=True, verbose_name='Historique familial')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patients')),
            ],
            options={
                'verbose_name': 'Antécédent Médical',
                'verbose_name_plural': 'Antécédents Médicaux',
                'managed': True,
                'indexes': [models.Index(fields=['patient'], name='patients_me_patient_9d2064_idx'), models.Index(fields=['date_recorded'], name='patients_me_date_re_c35ebb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient'], name='patients_co_patient_46c3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor'], name='patients_co_doctor__94d1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['date_recorded'], name='patients_co_date_re_94210e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation'], name='patients_pr_consult_cd8ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['date_recorded'], name='patients_pr_date_re_3ef270_idx'),
        ),
        migrations.AddIndex(
            model_name='transferedpatient',
            index=models.Index(fields=['transfer_date'], name='patients_tr_transfe_1785b8_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['patient'], name='patients_vi_patient_5f6c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['date_recorded'], name='patients_vi_date_re_2d29c2_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['patient', '-date_recorded'], name='patients_vi_patient_e94343_idx'),
        ),
    ]
