# Generated by Django 6.0.2 on 2026-04-17 17:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', unique=True, verbose_name='Contact📞')),
                ('adress', models.CharField(max_length=255, verbose_name='Adresse')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('tutor', models.CharField(max_length=100, verbose_name='Tuteur')),
                ('tutor_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CD', verbose_name='Contact du tuteur📞')),
                ('tutor_adress', models.CharField(max_length=255, verbose_name='Adresse du tuteur')),
                ('transfered', models.BooleanField(default=False, verbose_name='Transféré')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='Maladies Chroniques')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('long_term_treatments', models.TextField(blank=True, null=True, verbose_name='Traitements à Long Terme')),
                ('lifestyle_habits', models.TextField(blank=True, null=True, verbose_name='Habitudes de Vie')),
                ('family_history', models.TextField(blank=True, null=True, verbose_name='Historique familial')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patients')),
            ],
            options={
                'verbose_name': 'Antécédent Médical',
                'verbose_name_plural': 'Antécédents Médicaux',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_consultation', models.TextField(null=True, verbose_name='Raison de la Consultation')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnostic')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patients')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100, null=True, verbose_name='Nom du Médicament')),
                ('dosage', models.CharField(max_length=100, null=True, verbose_name='Dosage')),
                ('frequency', models.CharField(max_length=100, null=True, verbose_name='Fréquence')),
                ('duration', models.CharField(max_length=100, null=True, verbose_name='Durée')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.consultation')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransferedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motif du Transfert')),
                ('receiving_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Établissement Receveur')),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_info', to='patients.patients')),
            ],
            options={
                'verbose_name': 'Patient Transféré',
                'verbose_name_plural': 'Patients Transférés',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque (bpm)')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='Saturation en oxygène (%)')),
                ('blood_pressure', models.CharField(blank=True, max_length=7, null=True, verbose_name='Tension artérielle (mmHg)')),
                ('pulse', models.IntegerField(blank=True, null=True, verbose_name='Pouls (bpm)')),
                ('respiration_rate', models.IntegerField(blank=True, null=True, verbose_name='Fréquence respiratoire (respirations/min)')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patients')),
            ],
            options={
                'verbose_name': 'Signe Vital',
                'verbose_name_plural': 'Signes Vitaux',
                'managed': True,
            },
        ),
    ]
