# Generated by Django 6.0.2 on 2026-05-01 16:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('staff', '0005_remove_staff_title_staff_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000)], verbose_name='Dosage (mg)'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='tutor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuteur'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='tutor_adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse du tuteur'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('1x/day', '1 fois par jour'), ('2x/day', '2 fois par jour'), ('3x/day', '3 fois par jour'), ('4x/day', '4 fois par jour'), ('every_6h', 'Toutes les 6 heures'), ('every_8h', 'Toutes les 8 heures'), ('every_12h', 'Toutes les 12 heures'), ('as_needed', 'Si nécessaire')], max_length=20, null=True, verbose_name='Fréquence'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication_name',
            field=models.CharField(choices=[('paracetamol', 'Paracétamol'), ('ibuprofene', 'Ibuprofène'), ('amoxicilline', 'Amoxicilline'), ('azithromycine', 'Azithromycine'), ('metformine', 'Metformine'), ('atorvastatine', 'Atorvastatine'), ('lisinopril', 'Lisinopril'), ('autre', 'Autre')], max_length=100, null=True, verbose_name='Nom du Médicament'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)], verbose_name='Fréquence cardiaque (bpm)'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Saturation en oxygène (%)'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='pulse',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)], verbose_name='Pouls (bpm)'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='respiration_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(60)], verbose_name='Fréquence respiratoire (respirations/min)'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(42)], verbose_name='Température (°C)'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient'], name='patients_co_patient_46c3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor'], name='patients_co_doctor__94d1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['date_recorded'], name='patients_co_date_re_94210e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['patient'], name='patients_me_patient_9d2064_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['date_recorded'], name='patients_me_date_re_c35ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['email'], name='patients_pa_email_81a01f_idx'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['contact'], name='patients_pa_contact_f3546e_idx'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['registered_at'], name='patients_pa_registe_713ace_idx'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['first_name', 'last_name'], name='patients_pa_first_n_26d9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['registered_at'], name='patient_registered_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation'], name='patients_pr_consult_cd8ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['date_recorded'], name='patients_pr_date_re_3ef270_idx'),
        ),
        migrations.AddIndex(
            model_name='transferedpatient',
            index=models.Index(fields=['transfer_date'], name='patients_tr_transfe_1785b8_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['patient'], name='patients_vi_patient_5f6c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['date_recorded'], name='patients_vi_date_re_2d29c2_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['patient', '-date_recorded'], name='patients_vi_patient_e94343_idx'),
        ),
    ]
