# Generated by Django 6.0.2 on 2026-05-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_consultation_user_remove_patients_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['transfered'], name='patients_pa_transfe_b46abd_idx'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['sexe'], name='patients_pa_sexe_1ad407_idx'),
        ),
    ]
