# Generated by Django 6.0.2 on 2026-04-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_departement_staff_facebook_staff_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('subtitle', models.CharField(max_length=100, verbose_name='subtitle')),
                ('year', models.DateField(verbose_name='Année de  creation')),
                ('goal', models.TextField(verbose_name='Objectif')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='about/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'A propos',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom Hopital')),
                ('operation_days_time', models.CharField(max_length=150, verbose_name='jours et heures de service')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('address', models.CharField(max_length=100, verbose_name='adresse')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Lien facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Lien x(twitter)')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Lien instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='lien linkedin')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'urgence',
                'verbose_name_plural': 'urgence',
            },
        ),
        migrations.CreateModel(
            name='EmergencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('address', models.CharField(max_length=100, verbose_name='adresse')),
                ('operation_time', models.TextField(verbose_name='heures et jours de travail')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'urgence info',
                'verbose_name_plural': 'urgence info',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('subtitle', models.CharField(max_length=100, verbose_name='subtitle')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heros',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.CharField(max_length=100, verbose_name='icone')),
                ('short_description', models.TextField(verbose_name='description courte')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.departement', verbose_name='departement')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
