# Generated by Django 6.0.2 on 2026-04-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('staff', '0002_departement_staff_facebook_staff_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Departement',
        ),
        migrations.AddField(
            model_name='about',
            name='care_quality',
            field=models.TextField(blank=True, null=True, verbose_name='qualité de soin'),
        ),
        migrations.AddField(
            model_name='about',
            name='compassionate_care',
            field=models.TextField(blank=True, null=True, verbose_name='soin compassionnel'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.departement', verbose_name='departement'),
        ),
    ]
