# Generated by Django 6.0.2 on 2026-05-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
        ('patients', '0003_patients_patients_pa_transfe_b46abd_idx_and_more'),
        ('staff', '0006_staff_staff_staff_is_acti_a8a89f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['staff', 'date', 'time'], name='appointment_staff_i_8a77f7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'date'], name='appointment_patient_cdab7a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='appointment_date_cdab54_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['staff', 'accept'], name='appointment_staff_i_3d83e4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='appointment_created_1cd9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['staff', 'date', 'time'], name='appointment_slot_idx'),
        ),
    ]
