# Generated by Django 6.0.2 on 2026-05-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_appointment_staff_i_8a77f7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='raison',
            field=models.TextField(blank=True, help_text='Raison ou motif de la consultation', null=True, verbose_name='Motif du rendez-vous'),
        ),
    ]
