# Generated by Django 6.0.2 on 2026-05-08 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='departements/', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de famille')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('specialty', models.CharField(blank=True, choices=[('CHIRURGIE', 'Chirurgie'), ('ANESTHESISTE', 'Anesthsiste'), ('RADIOLOGUE', 'Radiologue'), ('PEDIATRE', 'Pédiatre'), ('GYNAECOLOGUE', 'Gynecologue'), ('DENTISTE', 'Dentiste'), ('OPHTALMOLOGUE', 'Ophtalmologue'), ('ORTHOPEDISTE', 'Orthopediste'), ('PATHOLOGUE', 'Pathologue'), ('PSYCHIATRE', 'Psychiatre'), ('THERAPEUTE', 'Therapeute')], max_length=100, null=True, verbose_name='Spécialité')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('role', models.CharField(choices=[('DOCTOR', 'Docteur'), ('NURSE', 'Infirmier'), ('MEDECIN', 'Medecin'), ('ADMIN', 'Administrateur'), ('LAB_TECH', 'Technicien de laboratoire'), ('PHARMACIST', 'Pharmacien'), ('SECRETARY', 'Secrtaire')], default='MEDECIN', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.departement', verbose_name='Departement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Membres du personnel',
            },
        ),
        migrations.CreateModel(
            name='TimeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=20, verbose_name='Jours de service')),
                ('open_time', models.TimeField(verbose_name="Heure d'ouverture")),
                ('close_time', models.TimeField(verbose_name='Heure de cloture')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_service', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Temps de service',
                'verbose_name_plural': 'Temps de service',
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active', 'is_verified'], name='staff_staff_is_acti_a8a89f_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['role'], name='staff_staff_role_423c94_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['departement'], name='staff_staff_departe_e2c87a_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['specialty'], name='staff_staff_special_b1b5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active', 'is_verified', 'role'], name='staff_active_role_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeservice',
            unique_together={('staff', 'service_day')},
        ),
    ]
