# Generated by Django 6.0.2 on 2026-04-17 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('role', models.CharField(choices=[('DOCTOR', 'Medecin'), ('NURSE', 'Medecin'), ('ADMIN', 'Administrateur'), ('LAB_TECH', 'Technicien de laboratoire'), ('PHARMACIST', 'Pharmacien'), ('SECRETARY', 'Secrtaire')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Membres du personnel',
            },
        ),
        migrations.CreateModel(
            name='TimeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=20, verbose_name='Jours de service')),
                ('open_time', models.TimeField(verbose_name="Heure d'ouverture")),
                ('close_time', models.TimeField(verbose_name='Heure de cloture')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_service', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Temps de service',
                'verbose_name_plural': 'Temps de service',
                'unique_together': {('staff', 'service_day')},
            },
        ),
    ]
