# Generated by Django 6.0.2 on 2026-04-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_departement_staff_facebook_staff_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='icon',
        ),
    ]
