# Generated by Django 6.0.2 on 2026-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_departement_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('DOCTOR', 'Dr.'), ('MEDECIN', 'Sp.'), ('CHIRURGIE', 'Chir.'), ('ANESTHESISTE', 'Anesth.'), ('RADIOLOGUE', 'Rad.'), ('PEDIATRE', 'Péd.'), ('GYNAECOLOGUE', 'Gyn.'), ('DENTISTE', 'Dent.'), ('OPHTALMOLOGUE', 'Ophtal.'), ('ORTHOPEDISTE', 'Ortho.'), ('OTORHINOLARYNGOLOGUE', 'Otorhino.'), ('PATHOLOGUE', 'Path.'), ('PSYCHIATRE', 'Psy.'), ('THERAPEUTE', 'Ther.'), ('INFIRMIER', 'Inf.')], default='INFIRMIER', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
