# Generated by Django 6.0.2 on 2026-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_title_alter_staff_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='title',
        ),
        migrations.AddField(
            model_name='staff',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Docteur'), ('NURSE', 'Infirmier'), ('MEDECIN', 'Medecin'), ('ADMIN', 'Administrateur'), ('LAB_TECH', 'Technicien de laboratoire'), ('PHARMACIST', 'Pharmacien'), ('SECRETARY', 'Secrtaire')], default='MEDECIN', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialty',
            field=models.CharField(blank=True, choices=[('CHIRURGIE', 'Chirurgie'), ('ANESTHESISTE', 'Anesthsiste'), ('RADIOLOGUE', 'Radiologue'), ('PEDIATRE', 'Pédiatre'), ('GYNAECOLOGUE', 'Gynecologue'), ('DENTISTE', 'Dentiste'), ('OPHTALMOLOGUE', 'Ophtalmologue'), ('ORTHOPEDISTE', 'Orthopediste'), ('PATHOLOGUE', 'Pathologue'), ('PSYCHIATRE', 'Psychiatre'), ('THERAPEUTE', 'Therapeute')], max_length=100, null=True, verbose_name='Spécialité'),
        ),
    ]
