# Generated by Django 6.0.2 on 2026-05-01 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_staff_title_staff_experience_years_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active', 'is_verified'], name='staff_staff_is_acti_a8a89f_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['role'], name='staff_staff_role_423c94_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['departement'], name='staff_staff_departe_e2c87a_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['specialty'], name='staff_staff_special_b1b5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active', 'is_verified', 'role'], name='staff_active_role_idx'),
        ),
    ]
